[build]
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "functions"  # Optional, specify the functions directory if using Netlify Functions
  publish = "build"        # Optional, specify the directory to publish (where the built files are)
